from fpdf import FPDF
import os

FONT_DIR = "utils/assets/fonts"

def register_custom_fonts(pdf: FPDF):
    """Registers DejaVu fonts from the assets/fonts directory."""
    try:
        pdf.add_font("DejaVu", "", os.path.join(FONT_DIR, "DejaVuSans.ttf"), uni=True)
        pdf.add_font("DejaVu", "B", os.path.join(FONT_DIR, "DejaVuSans-Bold.ttf"), uni=True)
        pdf.add_font("DejaVu", "I", os.path.join(FONT_DIR, "DejaVuSans-Oblique.ttf"), uni=True)
        pdf.add_font("DejaVu", "BI", os.path.join(FONT_DIR, "DejaVuSans-BoldOblique.ttf"), uni=True)
    except RuntimeError as e:
        print(f"Font registration failed: {e}")

def set_pdf_metadata(pdf: FPDF):
    """Sets basic metadata for the PDF."""
    pdf.set_title("Data Impact Report")
    pdf.set_author("Dynamic Impact Tool")
    pdf.set_creator("Dynamic Impact Tool - Streamlit App")
    pdf.set_subject("Automatically generated data analysis and insights report")

def add_cover_page(pdf: FPDF):
    """Adds a simple cover page to the PDF."""
    pdf.add_page()
    pdf.set_font("DejaVu", "B", 24)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 60, ln=True)  # Spacer
    pdf.cell(0, 10, "Dynamic Impact Report", ln=True, align="C")
    pdf.set_font("DejaVu", "", 14)
    pdf.cell(0, 10, "Generated by Dynamic Impact Tool", ln=True, align="C")

def add_table_of_contents(pdf: FPDF):
    """Adds a placeholder for a table of contents."""
    pdf.add_page()
    pdf.set_font("DejaVu", "B", 18)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "Table of Contents", ln=True)
    pdf.set_font("DejaVu", "", 12)
    pdf.set_text_color(60, 60, 60)

    contents = [
        "1. Executive Summary",
        "2. Introduction",
        "3. Data Overview",
        "4. Methodology",
        "5. Detailed Analysis & Insights",
        "   - Category-wise Analysis",
        "   - Trend & Pattern Identification",
        "   - Statistical Summary",
        "6. Cross-Domain Insights",
        "7. Recommendations & Actionable Items",
        "8. Conclusion"
    ]

    for line in contents:
        pdf.cell(0, 8, line, ln=True)

def add_section_heading(pdf: FPDF, title: str, level: int = 1):
    """Adds a styled heading to a new section."""
    font_size = 16 if level == 1 else 14
    font_style = "B" if level == 1 else ""
    pdf.set_font("DejaVu", font_style, font_size)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, title, ln=True)

def add_paragraph(pdf: FPDF, text: str):
    """Adds a formatted paragraph with word wrap."""
    pdf.set_font("DejaVu", "", 12)
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(0, 8, text, align="L")

def add_line_break(pdf: FPDF, height: int = 6):
    """Adds a vertical space."""
    pdf.ln(height)

def add_section_title(self, title):
    self.set_font("DejaVu", "B", 14)
    self.set_text_color(0, 0, 128)  # Dark blue
    self.multi_cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
    self.ln(2)
